"""The prepared order, the per-field delta, and the idempotency key -- PURE.

NO DB, NO network, NO transaction management (the Phase-12 classifier
convention). Everything here is a pure function of its arguments.

Arc 21-B. `compute_prepared_order` lands with Task 2; the digest helpers land
with Task 1 because the ledger's UNIQUE key is derived from them.
"""
from __future__ import annotations

import hashlib

from swing.latches.constants import DERIVATION_FIELD_MANIFEST


def _digest(*parts: str) -> str:
    """A LENGTH-PREFIXED sha256 over the parts. NEVER delimiter-joined.

    A single-character '|' join is ambiguous the moment a component can CONTAIN
    that character -- and one of them is `decline_reason`, FREE OPERATOR TEXT.
    Two different decisions could then produce the same pre-hash string and
    collapse onto one ledger row, or replay the wrong one. Length-prefixing makes
    the encoding INJECTIVE, so distinct inputs cannot share a digest.
    """
    h = hashlib.sha256()
    for part in parts:
        raw = part.encode("utf-8")
        h.update(str(len(raw)).encode("ascii"))
        h.update(b":")
        h.update(raw)
    return h.hexdigest()


def encode_derivation_value(encoding: str, value) -> str:
    """Canonical hidden-input / digest encoding for one derivation value.

    This is what makes the anchor digest REPRODUCIBLE across render and POST.
    A NULL encodes as the EMPTY STRING -- deliberately distinct from "0", which
    a float field could legitimately produce.
    """
    if value is None:
        return ""
    if encoding == "price2":
        return f"{float(value):.2f}"
    if encoding == "pct4":
        return f"{float(value):.4f}"
    if encoding == "int":
        return str(int(value))
    if encoding == "session":
        return str(value)
    if encoding == "text":
        return str(value)
    raise ValueError(f"unknown derivation encoding: {encoding!r}")


# The framework-order hidden fields, in a fixed order. The DERIVATION half is
# GENERATED by walking DERIVATION_FIELD_MANIFEST, so no site re-lists the
# derivation columns and the form, the digest and the POST-time comparison
# cannot drift from the schema (plan section A.4).
FRAMEWORK_ANCHOR_FIELDS: tuple[tuple[str, str], ...] = (
    ("framework_order_type", "text"),
    ("framework_duration", "text"),
    ("framework_stop_price", "price2"),
    ("framework_limit_price", "price2"),
    ("framework_quantity", "int"),
)


def derivation_anchor_fields() -> tuple[tuple[str, str], ...]:
    """`(column, encoding)` per manifest row -- the ONLY enumeration."""
    return tuple(
        (f.column, f.encode) for f in DERIVATION_FIELD_MANIFEST
    )


def build_anchor_digest(*, intent_kind: str, candidate_id: int,
                        view_session_date: str, values: dict) -> str:
    """The digest of the hidden anchor, KIND-SCOPED (plan section G.1).

    `place` / `decline` -- the canonical serialisation of EVERY hidden field the
    form emitted (`view_session_date`, `candidate_id`, the framework block and
    one component per manifest row), exactly as SUBMITTED. It is NOT the session
    anchor alone: if the key covered only the session and the operator's answer,
    a tampered or stale form carrying a DIFFERENT framework order but the same
    session and answer would hit the replay SELECT and return 200 WITHOUT ever
    reaching the field-by-field comparison -- a laundering path straight through
    the hidden-anchor defence.

    `validity` / `cancel` / `attest` -- the digest of `candidate_id` ALONE.
    These kinds submit NO framework block (the schema makes one unwritable on
    them), so there is no framework anchor to launder and nothing for that
    defence to protect; what remains of the old definition is exactly the
    render-time session, which is what BREAKS REPLAY across a session boundary.
    `view_session_date` stays fully load-bearing as a VALIDATION on every kind
    (the four-tier ladder still runs) -- it simply stops being KEY material
    where it cannot discriminate. A gate is not a key input.
    """
    if intent_kind in ("place", "decline"):
        parts = ["v1", str(candidate_id), view_session_date]
        for name, enc in FRAMEWORK_ANCHOR_FIELDS:
            parts.append(name)
            parts.append(encode_derivation_value(enc, values.get(name)))
        for column, enc in derivation_anchor_fields():
            parts.append(column)
            parts.append(encode_derivation_value(enc, values.get(column)))
        return _digest(*parts)
    return _digest("v1", str(candidate_id))


def build_idempotency_key(
    *, candidate_id: int, action_session_date: str, surface: str,
    intent_kind: str, anchor_digest: str, actual_digest: str,
    validated_place_intent_id: int | None = None,
) -> str:
    """The CONTENT-DERIVED per-latch idempotency key (hazard (a)).

    Content-derived, NOT a render-time nonce, so a REFRESH followed by an
    identical resubmit also collapses (a nonce would not).

    THE SESSION COMPONENT IS KIND-SCOPED, and it is NOT always
    `action_session_date`. Since a `validity` row's `action_session_date` is
    SERVER-COPIED from its parent, using it here would force a parent-row DB
    READ *before* the replay SELECT -- breaking the load-bearing property that
    EVERY key input is a function of the SUBMITTED PAYLOAD ALONE, which is
    exactly what lets the shape-validate step precede the replay step.

    No discriminating power is lost on the validity branch: two answers about
    DIFFERENT parents differ via `validated_place_intent_id` (here AND in
    `actual_digest`); two DIFFERENT answers about the SAME parent differ via
    `validity_outcome` (in `actual_digest`); two IDENTICAL answers about the same
    parent are the replay this key exists to collapse. And because the ledger is
    append-only, `validated_place_intent_id -> action_session_date` is an
    IMMUTABLE function -- so the parent link is a strictly BETTER stand-in for
    the mandate session than the anchor, which moves every day.

    `surface` is in the key because the table makes it a first-class NOT NULL
    column: without it, an identical decision taken from a second surface would
    collapse onto the first row and the ledger would lose which surface actually
    wrote the intent.
    """
    if intent_kind == "validity":
        if validated_place_intent_id is None:
            raise ValueError(
                "a validity key REQUIRES validated_place_intent_id -- it is the "
                "session component")
        session_component = f"parent:{validated_place_intent_id}"
    else:
        session_component = action_session_date
    return _digest(
        "v1", str(candidate_id), session_component, surface, intent_kind,
        anchor_digest, actual_digest)
