"""The prepared order, the per-field delta, and the idempotency key -- PURE.

NO DB, NO network, NO transaction management (the Phase-12 classifier
convention). Everything here is a pure function of its arguments.

Arc 21-B. `compute_prepared_order` lands with Task 2; the digest helpers land
with Task 1 because the ledger's UNIQUE key is derived from them.
"""
from __future__ import annotations

import hashlib
import math as _math
from dataclasses import dataclass as _dataclass
from decimal import ROUND_FLOOR as _ROUND_FLOOR
from decimal import Decimal as _Decimal

from swing.latches.constants import (
    DERIVATION_FIELD_MANIFEST,
    LATCH_ORDER_WITHHELD_REASONS,
    LATCH_STOP_LEG_STATES,
    LATCH_ZONE_CAP_PCT,
    MANDATE_ORDER_DURATIONS,
    MANDATE_ORDER_TYPE_BREAKOUT,
)
from swing.recommendations.sizing import compute_shares

# The ONLY member of MANDATE_ORDER_DURATIONS -- resolved FROM the frozenset so no
# site re-types the literal. GTC-ness is required of BOTH mandate forms: a DAY
# order expires tonight and leaves the operator uncovered tomorrow, which is how
# FTRE was lost.
(MANDATE_ORDER_DURATION,) = tuple(MANDATE_ORDER_DURATIONS)


def _digest(*parts: str) -> str:
    """A LENGTH-PREFIXED sha256 over the parts. NEVER delimiter-joined.

    A single-character '|' join is ambiguous the moment a component can CONTAIN
    that character -- and one of them is `decline_reason`, FREE OPERATOR TEXT.
    Two different decisions could then produce the same pre-hash string and
    collapse onto one ledger row, or replay the wrong one. Length-prefixing makes
    the encoding INJECTIVE, so distinct inputs cannot share a digest.
    """
    h = hashlib.sha256()
    for part in parts:
        raw = part.encode("utf-8")
        h.update(str(len(raw)).encode("ascii"))
        h.update(b":")
        h.update(raw)
    return h.hexdigest()


def encode_derivation_value(encoding: str, value) -> str:
    """Canonical hidden-input / digest encoding for one derivation value.

    This is what makes the anchor digest REPRODUCIBLE across render and POST.
    A NULL encodes as the EMPTY STRING -- deliberately distinct from "0", which
    a float field could legitimately produce.

    IT IS IDEMPOTENT, AND THAT IS LOAD-BEARING RATHER THAN TIDY. The render
    encodes RAW derivation values into hidden inputs; the browser posts those
    STRINGS back; the handler must recompute the SAME digest from what it
    received. If encoding a already-encoded value did not reproduce it, the two
    sides could not agree -- and the empty string in particular would raise
    (`float("")`) rather than encode, so a pullback mandate (whose framework
    stop leg is legitimately absent) could not be anchored at all.
    """
    if value is None or value == "":
        return ""
    if encoding == "price2":
        return f"{float(value):.2f}"
    if encoding == "pct6":
        # SIX decimals of FRACTION, i.e. four of PERCENT -- one digit FINER than
        # the card's `{rate*100:.3f}%`. The anchor must be at least as fine as
        # the display or two visibly-different rates share one hidden anchor and
        # the ledger stores a provenance the operator never saw.
        return f"{float(value):.6f}"
    if encoding == "int":
        return str(int(value))
    if encoding == "session":
        return str(value)
    if encoding == "text":
        return str(value)
    raise ValueError(f"unknown derivation encoding: {encoding!r}")


# The framework-order hidden fields, in a fixed order. The DERIVATION half is
# GENERATED by walking DERIVATION_FIELD_MANIFEST, so no site re-lists the
# derivation columns and the form, the digest and the POST-time comparison
# cannot drift from the schema (plan section A.4).
FRAMEWORK_ANCHOR_FIELDS: tuple[tuple[str, str], ...] = (
    ("framework_order_type", "text"),
    ("framework_duration", "text"),
    ("framework_stop_price", "price2"),
    ("framework_limit_price", "price2"),
    ("framework_quantity", "int"),
)


def derivation_anchor_fields() -> tuple[tuple[str, str], ...]:
    """`(column, encoding)` per manifest row -- the ONLY enumeration."""
    return tuple(
        (f.column, f.encode) for f in DERIVATION_FIELD_MANIFEST
    )


def build_anchor_digest(*, intent_kind: str, candidate_id: int,
                        view_session_date: str, values: dict) -> str:
    """The digest of the hidden anchor, KIND-SCOPED (plan section G.1).

    `place` / `decline` -- the canonical serialisation of EVERY hidden field the
    form emitted (`view_session_date`, `candidate_id`, the framework block and
    one component per manifest row), exactly as SUBMITTED. It is NOT the session
    anchor alone: if the key covered only the session and the operator's answer,
    a tampered or stale form carrying a DIFFERENT framework order but the same
    session and answer would hit the replay SELECT and return 200 WITHOUT ever
    reaching the field-by-field comparison -- a laundering path straight through
    the hidden-anchor defence.

    `validity` / `cancel` / `attest` -- the digest of `candidate_id` ALONE.
    These kinds submit NO framework block (the schema makes one unwritable on
    them), so there is no framework anchor to launder and nothing for that
    defence to protect; what remains of the old definition is exactly the
    render-time session, which is what BREAKS REPLAY across a session boundary.
    `view_session_date` stays fully load-bearing as a VALIDATION on every kind
    (the four-tier ladder still runs) -- it simply stops being KEY material
    where it cannot discriminate. A gate is not a key input.
    """
    if intent_kind in ("place", "decline"):
        parts = ["v1", str(candidate_id), view_session_date]
        for name, enc in FRAMEWORK_ANCHOR_FIELDS:
            parts.append(name)
            parts.append(encode_derivation_value(enc, values.get(name)))
        for column, enc in derivation_anchor_fields():
            parts.append(column)
            parts.append(encode_derivation_value(enc, values.get(column)))
        return _digest(*parts)
    return _digest("v1", str(candidate_id))


def build_idempotency_key(
    *, candidate_id: int, action_session_date: str, surface: str,
    intent_kind: str, anchor_digest: str, actual_digest: str,
    validated_place_intent_id: int | None = None,
    prior_intent_id: str = "",
) -> str:
    """The CONTENT-DERIVED per-latch idempotency key (hazard (a)).

    Content-derived, NOT a render-time nonce, so a REFRESH followed by an
    identical resubmit also collapses (a nonce would not).

    THE KEY IS SCOPED TO THE SUBMISSION IN CONTEXT (RD ruling 3, 2026-07-30).
    `prior_intent_id` is the row that GOVERNED this latch when the form was
    RENDERED -- empty when the latch had none.

    WHY IT IS THERE. The ledger's unit is the EVENT, not the VALUE, and a key
    that collapses on value cannot distinguish a REPLAY from a CORRECTION: the
    two are identical in value and differ only in context. `chose_not_to_act` ->
    `was_away` -> `chose_not_to_act` therefore reused the FIRST row's key, so
    the operator's actual FINAL answer was discarded as a replay and the
    flattering intermediate kept governing. The governing answer is his LAST,
    never his last DISTINCT, and a correction back to a prior value is a new act
    at a new time that MUST produce a new row in an append-only ledger.
    Preserving a flattering intermediate over his actual final answer is the
    instrument editing its subject's testimony in his favour.

    WHY IT IS A RENDER-TIME ANCHOR RATHER THAN A POST-TIME LOOKUP. Recomputing
    "the current governing row" at POST time would make the second click of a
    double-click see the row the FIRST click just wrote, key differently, and
    write a duplicate -- trading correction-fidelity for the double-click
    property. Both clicks of one render carry the SAME prior and still collapse.
    It also keeps the load-bearing property that EVERY key input is a function
    of the SUBMITTED PAYLOAD ALONE, which is what lets the shape check precede
    the replay SELECT.

    IT IS LATCH-SCOPED, NOT KIND-SCOPED, and that is ONE rule rather than five:
    the ledger is per-latch and append-only, the context IS the state of that
    latch's ledger as he saw it, and the place/decline form is a single form
    whose KIND is chosen at the submit button -- so a kind-scoped anchor could
    not be rendered by it at all.

    THE FORGERY HALF IS SCOPED OUT ON THE SAME GROUNDS SECTION F.3 ALREADY
    RECORDS for the broker snapshot: this is a `127.0.0.1` single-operator app,
    and a forged local POST implies an attacker who can already write the DB
    directly, where validating the anchor protects nothing. The realistic
    failure -- a STALE render, e.g. a second browser tab -- writes an EXTRA row
    rather than losing one, which is the safe direction on an append-only
    ledger: testimony is never destroyed, only duplicated, and the report dedupes
    on distinct latch identity.

    THE SESSION COMPONENT IS KIND-SCOPED, and it is NOT always
    `action_session_date`. Since a `validity` row's `action_session_date` is
    SERVER-COPIED from its parent, using it here would force a parent-row DB
    READ *before* the replay SELECT -- breaking the load-bearing property that
    EVERY key input is a function of the SUBMITTED PAYLOAD ALONE, which is
    exactly what lets the shape-validate step precede the replay step.

    No discriminating power is lost on the validity branch: two answers about
    DIFFERENT parents differ via `validated_place_intent_id` (here AND in
    `actual_digest`); two DIFFERENT answers about the SAME parent differ via
    `validity_outcome` (in `actual_digest`); two IDENTICAL answers about the same
    parent are the replay this key exists to collapse. And because the ledger is
    append-only, `validated_place_intent_id -> action_session_date` is an
    IMMUTABLE function -- so the parent link is a strictly BETTER stand-in for
    the mandate session than the anchor, which moves every day.

    `surface` is in the key because the table makes it a first-class NOT NULL
    column: without it, an identical decision taken from a second surface would
    collapse onto the first row and the ledger would lose which surface actually
    wrote the intent.
    """
    if intent_kind == "validity":
        if validated_place_intent_id is None:
            raise ValueError(
                "a validity key REQUIRES validated_place_intent_id -- it is the "
                "session component")
        session_component = f"parent:{validated_place_intent_id}"
    else:
        session_component = action_session_date
    return _digest(
        "v1", str(candidate_id), session_component, surface, intent_kind,
        anchor_digest, actual_digest, "prior", prior_intent_id)


# =====================================================================
# Task 2 -- the PREPARED ORDER and the PER-FIELD DELTA. Both PURE.
# =====================================================================


@_dataclass(frozen=True)
class OrderDerivation:
    """Every input that produced the four numbers, carried WITH them.

    The D25 lesson made structural: a human gate only helps if the human can SEE
    that a computation is wrong, and four bare numbers invite click-through. The
    renderer cannot show the numbers without this, because it travels on
    `PreparedOrder`.
    """

    latched_pivot: float
    latched_initial_stop: float
    zone_cap_pct: float
    fire_evaluation_run_id: int
    fire_session: str          # the FIRE's action_session_date
    fire_candidate_id: int
    regime_order_type: str | None
    regime_close: float | None
    regime_close_session: str | None
    sizing_basis: str          # limit_price (RD ruling) | pivot
    sizing_basis_price: float
    sizing_equity: float
    sizing_equity_source: str
    real_equity: float
    equity_floor: float
    max_risk_pct: float
    position_pct_cap: float
    risk_policy_id: int | None
    risk_per_share: float
    max_risk_dollars: float
    shares_by_risk: int
    shares_by_position_cap: int
    binding_constraint: str    # SizingResult.constraint
    nightly_recommendation_shares: int | None


@_dataclass(frozen=True)
class PreparedOrder:
    order_type: str            # STOP_LIMIT | LIMIT
    duration: str              # GOOD_TILL_CANCEL
    stop_price: float | None   # the frozen pivot in breakout; None in pullback
    limit_price: float         # the zone cap, cent-quantized DOWN
    quantity: int
    derivation: OrderDerivation


@_dataclass(frozen=True)
class PreparedOrderResult:
    """EXACTLY ONE of `order` / `withheld_reason` is non-None.

    A bare `PreparedOrder | None` return CANNOT carry the withheld reason the
    panel is required to render -- and the withheld branch is the CURRENT live
    state (the regime is undeterminable on today's substrate), so it is the
    branch that must be EXPRESSIVE, not the afterthought.
    """

    order: PreparedOrder | None
    withheld_reason: str | None
    withheld_detail: str

    def __post_init__(self) -> None:
        if (self.order is None) == (self.withheld_reason is None):
            raise ValueError(
                "EXACTLY ONE of order / withheld_reason must be set; got "
                f"order={self.order is not None}, "
                f"withheld_reason={self.withheld_reason!r}")
        if self.withheld_reason is not None:
            if self.withheld_reason not in LATCH_ORDER_WITHHELD_REASONS:
                raise ValueError(
                    "withheld_reason must be in "
                    f"{sorted(LATCH_ORDER_WITHHELD_REASONS)}, got "
                    f"{self.withheld_reason!r}")
            if not self.withheld_detail.strip():
                raise ValueError(
                    "a withheld form MUST carry display-ready detail -- an "
                    "unlabelled reduction is a quiet all-clear by omission")
        elif self.withheld_detail:
            raise ValueError(
                "withheld_detail must be '' when an order is present")


@_dataclass(frozen=True)
class SizingInputs:
    """The config- and policy-derived sizing context, gathered by the CALLER.

    Passed in rather than read, so `compute_prepared_order` stays PURE.
    """

    real_equity: float
    equity_floor: float
    sizing_equity: float
    max_risk_pct: float
    position_pct_cap: float
    risk_policy_id: int | None = None
    nightly_recommendation_shares: int | None = None


def quantize_limit_down(zone_cap: float) -> float:
    """The LARGEST WHOLE-CENT PRICE THAT DOES NOT EXCEED THE CAP, evaluated
    against the cap's DECIMAL value rather than its BINARY representation
    (RD ruling, 2026-07-30).

    WHOLE CENTS because that is the only price the order could actually be: a US
    equity limit order is penny-priced, 18.8902 is not a price the operator could
    enter, and this arc exists to put *the order he would place* in front of him.
    Rendering four decimals would make the card a number he must silently
    re-round himself -- the click-through invitation the derivation block exists
    to prevent.

    FLOOR, not round-half-up, and the reason is the CAP SEMANTIC: the zone cap is
    a MAXIMUM (pivot x 1.03 is the top of the buy zone), so a quantization that
    can move the price UP can push the order ABOVE the zone. Round-half-up does
    that whenever the cap's third decimal is >= 5 -- a cap of 18.8952 becomes
    18.90 > 18.8952. RD: a cap that can drift up under rounding is not a cap.

    AND NOT `math.floor(cap * 100) / 100` EITHER, which was the shipped form: a
    cap that IS an exact cent in decimal can be represented just BELOW it in
    binary, so the multiply-and-floor drops a cent that the decimal value plainly
    contains. `round(141.00 * 1.03, 4)` is `145.23`, but `145.23 * 100` evaluates
    to `14522.999999999998` and the naive floor emits **145.22**. Incidence
    through the production path (`zone_cap = round(pivot * 1.03, 4)`): 43 of the
    100,000 two-decimal pivots up to $1000.

    RARITY IS NOT THE ARGUMENT AND THE HARM IS NOT THE PRICE -- a limit one cent
    below the cap is still in zone and marginally conservative. The harm is that
    the FRAMEWORK THEN FLAGS ITS OWN OUTPUT AS A MISMATCH: 21-A's join compares a
    resting order's limit against the latch's cap at cent precision, so a
    145.22 order against a 145.23 cap attributes to NO latch, surfaces as a
    STRAY, and fires LATCH_ARMED_NO_RESTING_ORDER over a mandate the operator
    covered exactly as instructed. A false alarm we generate ourselves, on this
    arc's primary alarm channel, is the drumbeat-erosion class.

    `Decimal(str(cap))` is the mandated form rather than an epsilon or a
    `floor(round(cap * 100, 6))`: both of those work, and both need a precision
    constant nobody can justify to the next reader. `str()` yields the shortest
    decimal that round-trips the double, which IS "the cap's decimal value", and
    `ROUND_FLOOR` then states the cap semantic directly.

    FTRE does NOT exhibit either defect (18.8902 floors to 18.89 under every
    implementation), which is exactly why both rules have to be STATED rather
    than inferred from the worked example -- and why the two pinning tests are
    each marked NOT DROPPABLE: the round-half-up case passes under the naive
    floor, and the representation case passes under round-half-up.
    """
    return float(
        _Decimal(str(float(zone_cap))).quantize(
            _Decimal("0.01"), rounding=_ROUND_FLOOR))


def compute_prepared_order(
    *, latch, regime_order_type: str | None, regime_close: float | None,
    regime_close_session: str | None, sizing_inputs: SizingInputs,
) -> PreparedOrderResult:
    """The framework's computed entry order for `latch`, or a WITHHELD result.

    The regime is consumed through the EXISTING 21-A seam
    (`expected_mandate_order_type`) and NEVER re-implemented here, so whatever
    21-G does to make the close sound flows through automatically. When the
    regime is UNDETERMINABLE the form is WITHHELD: a form that guessed the type
    would write the WRONG TYPE into the parity ledger. That is the asymmetry rule
    again -- from a stale close you may raise a mismatch alarm, but you may not
    assert a match, and a prepared order IS an assertion.
    """
    if regime_order_type is None:
        return PreparedOrderResult(
            order=None, withheld_reason="regime_undeterminable",
            withheld_detail=(
                "No prepared order: the price regime is undeterminable, so the "
                "framework cannot tell a breakout stop-limit from a pullback "
                "limit. The mandate facts are shown; no order is offered."))

    limit_price = quantize_limit_down(latch.zone_cap)
    stop_price = (
        float(latch.latched_pivot)
        if regime_order_type == MANDATE_ORDER_TYPE_BREAKOUT else None)

    # RULED BY RD 2026-07-29: the LIMIT PRICE is the sizing basis in BOTH
    # regimes, NOT pivot-parity. In the pullback regime the limit is the only
    # price the order can fill at; in the breakout regime it is the worst case.
    # Pivot-basis sizing produces an order whose risk at an ordinary cap fill
    # BREACHES the policy cap -- and in the pullback regime the cap is PRECISELY
    # WHERE THE ORDER FILLS, so that is not a tail event. A mandate that breaches
    # the risk policy on the expected fill must not be rendered to the operator
    # as correct.
    sizing_basis_price = limit_price
    try:
        sizing = compute_shares(
            entry=sizing_basis_price, stop=float(latch.latched_initial_stop),
            equity=sizing_inputs.sizing_equity,
            max_risk_pct=sizing_inputs.max_risk_pct,
            position_pct_cap=sizing_inputs.position_pct_cap)
    except ValueError as exc:
        # `Latch.__post_init__` already guarantees
        # latched_initial_stop < latched_pivot < zone_cap, so this cannot fire --
        # but the call is guarded anyway and a raise DEGRADES VISIBLY (A6).
        return PreparedOrderResult(
            order=None, withheld_reason="sizing_degenerate",
            withheld_detail=(
                "No prepared order: the sizing computation is degenerate "
                f"({exc}). This is a framework defect, not a market state."))
    if not sizing.feasible:
        return PreparedOrderResult(
            order=None, withheld_reason="sizing_infeasible",
            withheld_detail=(
                "No prepared order: position sizing is infeasible at this "
                f"geometry (constraint: {sizing.constraint}). At limit "
                f"{limit_price:.2f} against the fire-time stop "
                f"{float(latch.latched_initial_stop):.2f}, no whole-share "
                "position fits inside the risk policy."))

    risk_per_share = sizing_basis_price - float(latch.latched_initial_stop)
    max_risk_dollars = sizing_inputs.sizing_equity * sizing_inputs.max_risk_pct
    shares_by_risk = (
        _math.floor(max_risk_dollars / risk_per_share) if risk_per_share > 0
        else 0)
    shares_by_position_cap = _math.floor(
        (sizing_inputs.sizing_equity * sizing_inputs.position_pct_cap)
        / sizing_basis_price)
    floor_binds = sizing_inputs.sizing_equity != sizing_inputs.real_equity
    derivation = OrderDerivation(
        latched_pivot=float(latch.latched_pivot),
        latched_initial_stop=float(latch.latched_initial_stop),
        zone_cap_pct=LATCH_ZONE_CAP_PCT,
        fire_evaluation_run_id=latch.identity.evaluation_run_id,
        fire_session=latch.identity.detection_date,
        fire_candidate_id=latch.identity.candidate_id,
        regime_order_type=regime_order_type,
        regime_close=None if regime_close is None else float(regime_close),
        regime_close_session=regime_close_session,
        sizing_basis="limit_price",
        sizing_basis_price=sizing_basis_price,
        sizing_equity=sizing_inputs.sizing_equity,
        sizing_equity_source=(
            "max(real equity, risk_equity_floor)" if floor_binds
            else "real equity (above the risk_equity_floor)"),
        real_equity=sizing_inputs.real_equity,
        equity_floor=sizing_inputs.equity_floor,
        max_risk_pct=sizing_inputs.max_risk_pct,
        position_pct_cap=sizing_inputs.position_pct_cap,
        risk_policy_id=sizing_inputs.risk_policy_id,
        risk_per_share=risk_per_share,
        max_risk_dollars=max_risk_dollars,
        shares_by_risk=shares_by_risk,
        shares_by_position_cap=shares_by_position_cap,
        binding_constraint=sizing.constraint,
        nightly_recommendation_shares=(
            sizing_inputs.nightly_recommendation_shares),
    )
    return PreparedOrderResult(
        order=PreparedOrder(
            order_type=regime_order_type,
            duration=MANDATE_ORDER_DURATION,
            stop_price=stop_price,
            limit_price=limit_price,
            quantity=sizing.shares,
            derivation=derivation),
        withheld_reason=None, withheld_detail="")


def derivation_column_values(derivation: OrderDerivation) -> dict:
    """`{latch_order_intents column: value}` for EVERY manifest row.

    GENERATED by walking `DERIVATION_FIELD_MANIFEST`, so the form's hidden
    inputs, the anchor digest, the POST-time comparison and the persisted row all
    read the SAME mapping and no site re-lists the columns.
    """
    return {
        f.column: getattr(derivation, f.attr) for f in DERIVATION_FIELD_MANIFEST
    }


def framework_column_values(order: PreparedOrder) -> dict:
    """`{latch_order_intents column: value}` for the framework-order block."""
    return {
        "framework_order_type": order.order_type,
        "framework_duration": order.duration,
        "framework_stop_price": order.stop_price,
        "framework_limit_price": order.limit_price,
        "framework_quantity": order.quantity,
    }


def recompute_derived_display_values(row) -> dict:
    """Reproduce the card's DERIVED lines from a STORED ledger row.

    `risk_per_share`, `max_risk_dollars`, `shares_by_risk`,
    `shares_by_position_cap` and `binding_constraint` are NOT stored: they are
    pure functions of values that ARE stored plus `latched_initial_stop` (pinned
    exactly by `candidate_id`), so storing them would be the denormalisation a
    computed delta rejects. This function is what makes that claim CHECKABLE
    rather than asserted -- if any one of the five could not be recomputed, it
    would belong in the stored set.

    `row` carries the stored columns plus `latched_initial_stop`.
    """
    entry = float(row["framework_limit_price"])
    stop = float(row["latched_initial_stop"])
    equity = float(row["derivation_sizing_equity"])
    risk_per_share = entry - stop
    max_risk_dollars = equity * float(row["derivation_max_risk_pct"])
    shares_by_risk = (
        _math.floor(max_risk_dollars / risk_per_share) if risk_per_share > 0
        else 0)
    shares_by_position_cap = _math.floor(
        (equity * float(row["derivation_position_pct_cap"])) / entry)
    return {
        "risk_per_share": risk_per_share,
        "max_risk_dollars": max_risk_dollars,
        "shares_by_risk": shares_by_risk,
        "shares_by_position_cap": shares_by_position_cap,
        "binding_constraint": (
            "risk" if shares_by_risk <= shares_by_position_cap
            else "position_cap"),
    }


# ---------------------------------------------------------------------
# The PER-FIELD DELTA -- computed, never stored (plan section A.3).
# ---------------------------------------------------------------------
_PRICE_DP = 2

_DURATION_ALIASES = {
    "GTC": "GOOD_TILL_CANCEL",
    "GOOD_TILL_CANCEL": "GOOD_TILL_CANCEL",
    "GOOD_TILL_CANCELLED": "GOOD_TILL_CANCEL",
    "GOOD_TILL_CANCELED": "GOOD_TILL_CANCEL",
    "DAY": "DAY",
    "FILL_OR_KILL": "FILL_OR_KILL",
    "FOK": "FILL_OR_KILL",
    "IMMEDIATE_OR_CANCEL": "IMMEDIATE_OR_CANCEL",
    "IOC": "IMMEDIATE_OR_CANCEL",
    "END_OF_WEEK": "END_OF_WEEK",
    "END_OF_MONTH": "END_OF_MONTH",
    "NEXT_END_OF_MONTH": "NEXT_END_OF_MONTH",
}


def canonical_duration(raw) -> str:
    """Map a broker's duration rendering onto the framework's vocabulary.

    Comparing RAW strings would report `GTC` vs `GOOD_TILL_CANCEL` as a duration
    divergence on a SEMANTICALLY IDENTICAL order -- a manufactured mismatch in
    the exact metric the ledger exists to compute, and the mirror image of the
    instrument being unable to see a REAL divergence. The CANONICAL form is what
    is PERSISTED and what `duration_differs` compares.

    An unmapped duration canonicalises to `UNKNOWN`, and unknown is NEVER
    agreement.
    """
    if raw is None:
        return "UNKNOWN"
    return _DURATION_ALIASES.get(str(raw).strip().upper(), "UNKNOWN")


def framework_side_of(intent) -> dict | None:
    """The FRAMEWORK order side of a stored ledger row, or `None`.

    ONE mapper, because the CLI report and the validity prompt must reason about
    the same five fields in the same shape: the prompt's divergence note and the
    monthly agreement rate are the SAME comparison asked at two moments, and two
    hand-kept copies of the mapping is how they would stop agreeing.
    """
    if intent is None or getattr(intent, "framework_order_type", None) is None:
        return None
    return {
        "order_type": intent.framework_order_type,
        "duration": intent.framework_duration,
        "stop_price": intent.framework_stop_price,
        "limit_price": intent.framework_limit_price,
        "quantity": intent.framework_quantity,
    }


def observed_side_of(order) -> dict:
    """The ACTUAL order side of a live resting broker order.

    `duration` is CANONICALISED here for the same reason `compute_order_delta`
    canonicalises it: brokers render `GTC` where the framework stores
    `GOOD_TILL_CANCEL`, and comparing them raw reports a duration divergence on
    a semantically identical order.
    """
    return {
        "order_type": (getattr(order, "order_type", "") or "").upper() or None,
        "duration": canonical_duration(getattr(order, "duration", None)),
        "stop_price": getattr(order, "stop_price", None),
        "limit_price": getattr(order, "limit_price", None),
        "quantity": _integral_quantity(getattr(order, "quantity", None)),
    }


def _integral_quantity(raw) -> int | None:
    """A broker quantity as a whole number of shares, or `None` (UNKNOWN).

    `int(10.9)` TRUNCATES to 10 (Codex exec R8 MAJOR), and a framework quantity
    of 10 would then AGREE with a 10.9-share order -- the instrument fabricating
    an agreement out of a divergence, in the one metric it exists to compute.
    Truncating measurement evidence is never the conservative choice.

    UNKNOWN is: a non-integral quantity, a non-finite one, or an unreadable one.
    Unknown is never agreement (the rule 21-A's `_agreement_word` enforces), so
    `compute_order_delta` reports the quantity leg as unknown and
    `_observed_side_is_complete` withholds the CONFIRM control -- which is the
    honest reading of a share count the framework cannot represent.
    """
    if raw is None or isinstance(raw, bool):
        return None
    try:
        value = float(raw)
    except (TypeError, ValueError):
        return None
    if not _math.isfinite(value) or value != int(value):
        return None
    return int(value)


@_dataclass(frozen=True)
class OrderDelta:
    """Framework-vs-actual, per field, at DISPLAY precision.

    `None` means ONE SIDE IS UNKNOWN -- never `False`. Unknown is never
    agreement (the rule 21-A's `_agreement_word` already enforces).
    """

    order_type_differs: bool | None
    duration_differs: bool | None
    # THE STOP LEG IS TRI-STATE, not `float | None`. With a bare `float | None`,
    # "both sides correctly have no stop leg" (the PULLBACK regime's RIGHT
    # answer) and "one side is unknown" both collapse to None -- so a legitimate
    # EXACT MATCH would be reported as unknown, and unknown is never agreement,
    # so the CORRECT order would be scored as a non-match.
    stop_leg: str                        # both_absent | compared | unknown
    stop_price_delta: float | None       # set IFF stop_leg == 'compared'
    limit_price_delta: float | None
    quantity_delta: int | None
    any_difference: bool | None          # None when ANY field is unknown
    unknown_fields: tuple[str, ...]

    def __post_init__(self) -> None:
        if self.stop_leg not in LATCH_STOP_LEG_STATES:
            raise ValueError(
                f"stop_leg must be in {sorted(LATCH_STOP_LEG_STATES)}, "
                f"got {self.stop_leg!r}")
        if (self.stop_price_delta is not None) != (self.stop_leg == "compared"):
            raise ValueError(
                "stop_price_delta is set IFF stop_leg == 'compared'; got "
                f"stop_leg={self.stop_leg!r}, delta={self.stop_price_delta!r}")


_ORDER_FIELDS = (
    "order_type", "duration", "stop_price", "limit_price", "quantity")


def _round2(value) -> float | None:
    return None if value is None else round(float(value), _PRICE_DP)


def _as_order_mapping(side) -> dict:
    if side is None:
        return dict.fromkeys(_ORDER_FIELDS)
    if isinstance(side, dict):
        return {f: side.get(f) for f in _ORDER_FIELDS}
    return {f: getattr(side, f, None) for f in _ORDER_FIELDS}


def _resolve_stop_leg(fw: dict, ac: dict) -> tuple[str, float | None]:
    """`both_absent` | `compared` | `unknown`, and the delta iff `compared`.

    `unknown` covers BOTH "exactly one side carries a stop leg" and "the actual
    side is not observed at all" -- the two are indistinguishable in evidence
    terms from here, and both must contribute `None` rather than agreement.
    """
    ac_type = ac.get("order_type")
    fw_stop = _round2(fw.get("stop_price"))
    ac_stop = _round2(ac.get("stop_price"))
    if ac_type is None:
        # nothing observed -- not even the shape that would say whether a stop
        # leg was expected
        return "unknown", None
    if fw_stop is None and ac_stop is None:
        return "both_absent", None
    if fw_stop is None or ac_stop is None:
        return "unknown", None
    return "compared", round(ac_stop - fw_stop, _PRICE_DP)


def compute_order_delta(framework, actual) -> OrderDelta:
    """The execution-parity metric, computed at read time from BOTH sides.

    `framework` and `actual` are mappings/objects carrying `order_type`,
    `duration`, `stop_price`, `limit_price`, `quantity`. Either may be `None`
    (not observed), and any individual field may be `None`.

    Prices compare at DISPLAY precision (`round(a, 2) != round(b, 2)`), never as
    a raw float compare: at execution grain a sub-cent artifact would falsely
    flip an identical order to "operator edited".
    """
    fw = _as_order_mapping(framework)
    ac = _as_order_mapping(actual)
    unknown: list[str] = []

    fw_type, ac_type = fw.get("order_type"), ac.get("order_type")
    if fw_type is None or ac_type is None:
        unknown.append("order_type")
        order_type_differs = None
    else:
        order_type_differs = fw_type != ac_type

    # DURATIONS ARE CANONICALISED BEFORE COMPARISON, NOT COMPARED RAW.
    fw_dur = canonical_duration(fw.get("duration"))
    ac_dur = canonical_duration(ac.get("duration"))
    if "UNKNOWN" in (fw_dur, ac_dur):
        unknown.append("duration")
        duration_differs = None
    else:
        duration_differs = fw_dur != ac_dur

    limit_a, limit_b = _round2(fw.get("limit_price")), _round2(ac.get("limit_price"))
    if limit_a is None or limit_b is None:
        unknown.append("limit_price")
        limit_price_delta = None
    else:
        limit_price_delta = round(limit_b - limit_a, _PRICE_DP)

    qty_a, qty_b = fw.get("quantity"), ac.get("quantity")
    if qty_a is None or qty_b is None:
        unknown.append("quantity")
        quantity_delta = None
    else:
        quantity_delta = int(qty_b) - int(qty_a)

    stop_leg, stop_price_delta = _resolve_stop_leg(fw, ac)
    if stop_leg == "unknown":
        unknown.append("stop_price")

    differences = [
        order_type_differs, duration_differs,
        None if limit_price_delta is None else limit_price_delta != 0,
        None if quantity_delta is None else quantity_delta != 0,
    ]
    if stop_leg == "both_absent":
        # BOTH SIDES CORRECTLY HAVE NO STOP LEG -- this is a MATCH.
        differences.append(False)
    elif stop_leg == "compared":
        differences.append(stop_price_delta != 0)
    else:
        differences.append(None)

    any_difference = (
        None if any(d is None for d in differences) else any(differences))
    return OrderDelta(
        order_type_differs=order_type_differs,
        duration_differs=duration_differs,
        stop_leg=stop_leg,
        stop_price_delta=stop_price_delta,
        limit_price_delta=limit_price_delta,
        quantity_delta=quantity_delta,
        any_difference=any_difference,
        unknown_fields=tuple(sorted(set(unknown))),
    )
